#ifndef MULTIBOOT2_H
#define MULTIBOOT2_H

#define MULTIBOOT_SEARCH 32768
#define MULTIBOOT_HEADER_ALIGN 8

#define MULTIBOOT2_HEADER_MAGIC 0xE85250D6

#define MULTIBOOT_ARCHITECTURE_I386 0
#define MULTIBOOT_ARCHITECTURE_MIPS 4

#endif